backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: static/img
public_folder: /img
collections:

- name: 'event'
  label: 'Event'
  folder: 'content/event'
  create: true 
  delete: true
  slug: '{{title}}'
  editor:
    preview: false
  fields:
    - { label: 'Title', name: 'title', widget: 'string'}
    - { label: 'Draft', name: 'draft', widget: 'hidden', default: false }
    - { label: 'Description', name: 'description', widget: 'hidden', default: 'desc' }
    - { label: "Featured", name: "featured", widget: "boolean", default: false }
    - { label: 'URL', name: 'blogurl', widget: 'string', required: false}  
    - { label: 'Category', name: 'cat', widget: 'select', options: ['Category 1', 'Category 2', 'Category 3']}
    - { label: "Image File", name: "imgfile", widget: "image", required: false }
    - { label: 'Summary', name: 'summary', widget: 'text', required: false}
    - { label: 'Info', name: 'info', widget: 'markdown', required: false}